# Generated by Django 5.2.16 on 2026-08-13 06:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("corpora", "0005_alter_corpusdocumentation_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("retrieve", "证据检索"),
                            ("quality_review", "质量审阅"),
                            ("export", "检索后导出"),
                        ],
                        max_length=30,
                    ),
                ),
                ("skill", models.CharField(max_length=100, verbose_name="Skill 版本")),
                (
                    "idempotency_key",
                    models.CharField(max_length=128, verbose_name="幂等键"),
                ),
                (
                    "request_id",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="请求追踪 ID"
                    ),
                ),
                (
                    "request_fingerprint",
                    models.CharField(max_length=64, verbose_name="请求指纹"),
                ),
                ("plan", models.JSONField(default=dict, verbose_name="已验证执行计划")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待执行"),
                            ("running", "执行中"),
                            ("waiting_approval", "等待确认"),
                            ("succeeded", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="执行状态",
                    ),
                ),
                ("answer", models.TextField(blank=True, verbose_name="证据化回答")),
                (
                    "evidence",
                    models.JSONField(blank=True, default=list, verbose_name="证据引用"),
                ),
                (
                    "model_usage",
                    models.JSONField(blank=True, default=dict, verbose_name="模型用量"),
                ),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        decimal_places=8,
                        default=0,
                        max_digits=12,
                        verbose_name="预估模型成本(USD)",
                    ),
                ),
                (
                    "error_code",
                    models.CharField(blank=True, max_length=80, verbose_name="错误码"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误详情"),
                ),
                (
                    "attempt_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="执行尝试次数"
                    ),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="执行租约截止",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to="corpora.corpus",
                        verbose_name="语料库",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="请求用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent 运行",
                "verbose_name_plural": "Agent 运行",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="AgentApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("create_export", "创建导出任务")], max_length=40
                    ),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="待确认动作")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待确认"),
                            ("approved", "已确认"),
                            ("expired", "已过期"),
                            ("rejected", "已拒绝"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="确认截止时间"),
                ),
                (
                    "result",
                    models.JSONField(blank=True, default=dict, verbose_name="动作结果"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval",
                        to="agent.agentrun",
                        verbose_name="Agent 运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent 审批",
                "verbose_name_plural": "Agent 审批",
            },
        ),
        migrations.CreateModel(
            name="AgentStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="步骤序号",
                    ),
                ),
                ("node", models.CharField(max_length=80, verbose_name="工作流节点")),
                (
                    "tool_name",
                    models.CharField(blank=True, max_length=100, verbose_name="工具"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待执行"),
                            ("running", "执行中"),
                            ("succeeded", "已完成"),
                            ("failed", "失败"),
                            ("skipped", "已跳过"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("input", models.JSONField(default=dict, verbose_name="受控工具入参")),
                (
                    "output",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="脱敏工具结果"
                    ),
                ),
                (
                    "error_code",
                    models.CharField(blank=True, max_length=80, verbose_name="错误码"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误详情"),
                ),
                (
                    "attempt_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="尝试次数"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="agent.agentrun",
                        verbose_name="Agent 运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent 步骤",
                "verbose_name_plural": "Agent 步骤",
                "ordering": ["sequence"],
            },
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["requested_by", "status", "-created_at"],
                name="agent_run_user_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["corpus", "-created_at"], name="agent_run_corpus_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["status", "locked_until"], name="agent_run_lease_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentrun",
            constraint=models.UniqueConstraint(
                fields=("requested_by", "idempotency_key"),
                name="agent_run_user_idempotency_key",
            ),
        ),
        migrations.AddIndex(
            model_name="agentapproval",
            index=models.Index(
                fields=["status", "expires_at"], name="agent_approval_expiry_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentstep",
            constraint=models.UniqueConstraint(
                fields=("run", "sequence"), name="agent_step_run_sequence"
            ),
        ),
    ]
