# Generated by Django 5.2.16 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0001_corpus_agent_harness"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="external_wait_expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="外部等待超时"),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="external_wait_id",
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name="外部等待任务 ID"),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="external_wait_kind",
            field=models.CharField(
                blank=True,
                choices=[("parallel_audit", "等待平行语料质检")],
                max_length=40,
                verbose_name="外部等待类型",
            ),
        ),
        migrations.AlterField(
            model_name="agentrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "等待执行"),
                    ("running", "执行中"),
                    ("waiting_external", "等待外部任务"),
                    ("waiting_approval", "等待确认"),
                    ("succeeded", "已完成"),
                    ("failed", "失败"),
                    ("cancelled", "已取消"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
                verbose_name="执行状态",
            ),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["status", "external_wait_id"],
                name="agent_run_external_wait_idx",
            ),
        ),
    ]
