# Generated by Django 5.2.16 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0002_parallel_audit_saga"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="external_wait_started_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="外部等待开始时间"),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["status", "external_wait_started_at"],
                name="agent_run_wait_age_idx",
            ),
        ),
    ]
