# Generated by Django 5.2.16 on 2026-08-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("agent", "0003_external_wait_observability")]

    operations = [
        migrations.AlterField(
            model_name="agentrun",
            name="mode",
            field=models.CharField(
                choices=[
                    ("retrieve", "证据检索"),
                    ("rag", "混合 RAG 检索"),
                    ("quality_review", "质量审阅"),
                    ("export", "检索后导出"),
                ],
                max_length=30,
            ),
        )
    ]
