# Generated by Django 5.2.16 on 2026-07-13 07:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("corpora", "0003_alter_corpus_corpus_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("kwic", "KWIC"), ("parallel", "ParaConc")],
                        max_length=20,
                        verbose_name="导出类型",
                    ),
                ),
                ("query", models.JSONField(default=dict, verbose_name="查询条件")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待执行"),
                            ("running", "执行中"),
                            ("success", "可下载"),
                            ("failed", "失败"),
                            ("expired", "已过期"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="进度",
                    ),
                ),
                (
                    "output_path",
                    models.CharField(
                        blank=True, max_length=1500, verbose_name="导出文件"
                    ),
                ),
                (
                    "row_count",
                    models.PositiveBigIntegerField(default=0, verbose_name="结果行数"),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(default=0, verbose_name="下载次数"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="过期时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "last_downloaded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近下载"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to="corpora.corpus",
                        verbose_name="语料库",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
            ],
            options={
                "verbose_name": "导出任务",
                "verbose_name_plural": "导出任务",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["requested_by", "created_at"],
                        name="export_user_created_idx",
                    ),
                    models.Index(
                        fields=["corpus", "created_at"],
                        name="export_corpus_created_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["pending", "running"])),
                        fields=("requested_by",),
                        name="one_active_export_job_per_user",
                    )
                ],
            },
        ),
    ]
