# Generated by Django 5.1 on 2026-08-22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160, verbose_name="标题")),
                ("body", models.TextField(verbose_name="正文")),
                ("audience", models.CharField(choices=[("all", "全部已审核用户"), ("selected", "指定用户")], default="all", max_length=20, verbose_name="发布范围")),
                ("is_published", models.BooleanField(db_index=True, default=False, verbose_name="已发布")),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="开始展示")),
                ("ends_at", models.DateTimeField(blank=True, null=True, verbose_name="结束展示")),
                ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="发布时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_announcements", to=settings.AUTH_USER_MODEL, verbose_name="创建管理员")),
                ("published_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="published_announcements", to=settings.AUTH_USER_MODEL, verbose_name="发布管理员")),
            ],
            options={"verbose_name": "平台公告", "verbose_name_plural": "平台公告", "ordering": ["-is_published", "-starts_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="AnnouncementRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="添加时间")),
                ("announcement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recipient_links", to="admin_portal.announcement", verbose_name="公告")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="announcement_recipient_links", to=settings.AUTH_USER_MODEL, verbose_name="用户")),
            ],
            options={"verbose_name": "公告接收人", "verbose_name_plural": "公告接收人"},
        ),
        migrations.AddField(
            model_name="announcement",
            name="recipients",
            field=models.ManyToManyField(blank=True, related_name="received_announcements", through="admin_portal.AnnouncementRecipient", to=settings.AUTH_USER_MODEL, verbose_name="指定接收用户"),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(fields=["is_published", "starts_at"], name="announcement_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="announcementrecipient",
            constraint=models.UniqueConstraint(fields=("announcement", "user"), name="unique_announcement_recipient"),
        ),
    ]
