# Generated by Django 5.2.16 on 2026-07-13 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("corpora", "0003_alter_corpus_corpus_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login.success", "登录成功"),
                            ("login.failed", "登录失败"),
                            ("logout", "退出登录"),
                            ("search.kwic", "KWIC 检索"),
                            ("search.parallel", "ParaConc 检索"),
                            ("search.statistics", "统计分析"),
                            ("corpus.upload", "上传语料"),
                            ("corpus.retry", "重试加工"),
                            ("corpus.delete", "删除语料"),
                            ("quota.request", "申请扩容"),
                            ("export.created", "创建导出"),
                            ("export.completed", "导出完成"),
                            ("export.failed", "导出失败"),
                            ("export.downloaded", "下载导出"),
                            ("admin.action", "管理员操作"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="事件类型",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="请求路径"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="请求方法"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 地址"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User-Agent"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="事件数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="发生时间"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
                (
                    "corpus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="corpora.corpus",
                        verbose_name="语料库",
                    ),
                ),
            ],
            options={
                "verbose_name": "审计事件",
                "verbose_name_plural": "审计事件",
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["actor", "created_at"], name="audit_actor_created_idx"
                    ),
                    models.Index(
                        fields=["corpus", "created_at"], name="audit_corpus_created_idx"
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="audit_type_created_idx",
                    ),
                ],
            },
        ),
    ]
