# Generated by Django 5.2 on 2026-09-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0004_parallel_audit_saga"),
        ("corpora", "0006_corpus_access_grants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("kwic", "KWIC 检索"),
                            ("parallel", "ParaConc 平行检索"),
                            ("word_list", "词表"),
                            ("clusters", "词簇"),
                            ("ngrams", "N-Gram"),
                            ("collocates", "搭配词"),
                            ("keywords", "关键词"),
                            ("wordcloud", "词云"),
                            ("concordance_plot", "索引图"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="检索类型",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="名称")),
                ("query_string", models.TextField(verbose_name="查询参数")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="保存时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to="corpora.corpus",
                        verbose_name="语料库",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "已保存检索",
                "verbose_name_plural": "已保存检索",
                "ordering": ["-updated_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["user", "updated_at"],
                        name="saved_search_user_updated_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "corpus", "kind", "query_string"),
                        name="unique_saved_search_query_per_user",
                    )
                ],
            },
        )
    ]
