# Generated by Django 5.2.17 on 2026-09-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0005_savedsearch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login.success", "登录成功"),
                    ("login.failed", "登录失败"),
                    ("logout", "退出登录"),
                    ("search.kwic", "KWIC 检索"),
                    ("search.parallel", "ParaConc 检索"),
                    ("search.statistics", "统计分析"),
                    ("corpus.upload", "上传语料"),
                    ("corpus.retry", "重试加工"),
                    ("corpus.delete", "删除语料"),
                    ("quota.request", "申请扩容"),
                    ("export.created", "创建导出"),
                    ("export.completed", "导出完成"),
                    ("export.failed", "导出失败"),
                    ("export.downloaded", "下载导出"),
                    ("admin.action", "管理员操作"),
                ],
                db_index=True,
                max_length=40,
                verbose_name="事件类型",
            ),
        ),
    ]
