# Generated by Django 5.2.16 on 2026-08-11 05:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpora", "0004_query_indexes"),
        ("processing", "0002_processingtask_one_active_per_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="processingtask",
            index=models.Index(
                fields=["corpus", "-created_at"], name="processing_corpus_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processingtask",
            index=models.Index(
                fields=["requested_by", "status", "-created_at"],
                name="processing_request_status_idx",
            ),
        ),
    ]
