# Generated by Django 5.2.16 on 2026-07-10 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100, verbose_name="姓名")),
                ("organization", models.CharField(max_length=200, verbose_name="单位")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="申请邮箱"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("test", "测试用户"),
                            ("junior", "初级用户"),
                            ("middle", "中级用户"),
                            ("advanced", "高级用户"),
                            ("admin", "管理员"),
                        ],
                        db_index=True,
                        default="junior",
                        max_length=20,
                        verbose_name="当前等级",
                    ),
                ),
                (
                    "requested_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("junior", "初级用户"),
                            ("middle", "中级用户"),
                            ("advanced", "高级用户"),
                        ],
                        max_length=20,
                        verbose_name="申请等级",
                    ),
                ),
                (
                    "use_purpose",
                    models.CharField(max_length=200, verbose_name="使用目的"),
                ),
                ("application_reason", models.TextField(verbose_name="申请理由")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                            ("disabled", "已停用"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="申请状态",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_account_profiles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户申请与权限",
                "verbose_name_plural": "用户申请与权限",
                "ordering": ["-created_at"],
            },
        ),
    ]
