# Generated by Django 5.2.16 on 2026-07-13 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="upload_max_file_bytes",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="留空使用角色默认值。",
                null=True,
                verbose_name="单文件配额覆盖（字节）",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="upload_total_bytes",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="留空使用角色默认值。",
                null=True,
                verbose_name="总上传配额覆盖（字节）",
            ),
        ),
        migrations.CreateModel(
            name="UploadQuotaRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "requested_max_file_bytes",
                    models.PositiveBigIntegerField(verbose_name="申请单文件配额"),
                ),
                (
                    "requested_total_bytes",
                    models.PositiveBigIntegerField(verbose_name="申请总配额"),
                ),
                ("reason", models.TextField(verbose_name="申请理由")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_upload_quota_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_quota_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
            ],
            options={
                "verbose_name": "上传配额申请",
                "verbose_name_plural": "上传配额申请",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("user",),
                        name="one_pending_upload_quota_request_per_user",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "requested_max_file_bytes__lte",
                                models.F("requested_total_bytes"),
                            )
                        ),
                        name="upload_quota_request_max_lte_total",
                    ),
                ],
            },
        ),
    ]
