# Generated by Django 5.2.16 on 2026-08-12 09:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("corpora", "0004_query_indexes"),
        ("processing", "0005_alter_processingtask_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParallelAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待审计"),
                            ("running", "审计中"),
                            ("success", "审计完成"),
                            ("failed", "审计失败"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "report_path",
                    models.CharField(
                        blank=True, max_length=1500, verbose_name="报告路径"
                    ),
                ),
                (
                    "anomalies_path",
                    models.CharField(
                        blank=True, max_length=1500, verbose_name="异常明细路径"
                    ),
                ),
                (
                    "summary",
                    models.JSONField(blank=True, default=dict, verbose_name="审计摘要"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parallel_audits",
                        to="corpora.corpus",
                        verbose_name="语料库",
                    ),
                ),
                (
                    "processing_task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parallel_audit",
                        to="processing.processingtask",
                        verbose_name="来源加工任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "平行语料审计",
                "verbose_name_plural": "平行语料审计",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["corpus", "-created_at"],
                        name="parallel_audit_corpus_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="parallel_audit_status_idx",
                    ),
                ],
            },
        ),
    ]
