# Generated by Django 5.2.16 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parallelaudit",
            name="execution_mode",
            field=models.CharField(
                choices=[("remote", "Go service"), ("local", "Local fallback")],
                default="remote",
                max_length=20,
                verbose_name="Execution mode",
            ),
        ),
        migrations.AddField(
            model_name="parallelaudit",
            name="remote_attempt",
            field=models.PositiveIntegerField(default=0, verbose_name="Remote attempt"),
        ),
        migrations.AddField(
            model_name="parallelaudit",
            name="remote_callback_payload_hash",
            field=models.CharField(blank=True, max_length=64, verbose_name="Remote callback payload hash"),
        ),
        migrations.AddField(
            model_name="parallelaudit",
            name="remote_callback_received_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Remote callback received at"),
        ),
        migrations.AddField(
            model_name="parallelaudit",
            name="remote_job_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name="Remote job ID"),
        ),
        migrations.AddField(
            model_name="parallelaudit",
            name="remote_state",
            field=models.CharField(blank=True, max_length=32, verbose_name="Remote state"),
        ),
    ]
