# Generated by Django 5.2.16 on 2026-07-10 08:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Corpus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="语料库名称")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("teacher", "教师语料"),
                            ("demo", "演示语料"),
                            ("user", "用户自建语料"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="来源类型",
                    ),
                ),
                (
                    "corpus_type",
                    models.CharField(
                        choices=[
                            ("raw_zh", "中文原文"),
                            ("raw_en", "英文原文"),
                            ("aligned_tsv", "中英对齐 TSV"),
                            ("paired_raw_zh_en", "中英原文配对"),
                            ("tagged_zh", "中文词性标注"),
                            ("tagged_en", "英文词性标注"),
                            ("xml_like", "类 XML 结构"),
                            ("unknown", "待确认"),
                        ],
                        max_length=30,
                        verbose_name="语料类型",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("zh", "中文"),
                            ("en", "英文"),
                            ("zh_en", "中英双语"),
                            ("unknown", "待确认"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="语言",
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("demo", "演示范围"),
                            ("junior", "初级及以上"),
                            ("middle", "中级及以上"),
                            ("advanced", "高级及以上"),
                            ("private", "仅所有者"),
                        ],
                        db_index=True,
                        default="junior",
                        max_length=20,
                        verbose_name="访问等级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "已登记"),
                            ("pending_processing", "等待加工"),
                            ("processing", "加工中"),
                            ("ready", "可用"),
                            ("failed", "失败"),
                            ("disabled", "已停用"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=30,
                        verbose_name="状态",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        default="registered", max_length=50, verbose_name="当前阶段"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="说明")),
                (
                    "manifest_file_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="manifest 文件 ID",
                    ),
                ),
                (
                    "manifest_relative_path",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        verbose_name="manifest 原始相对路径",
                    ),
                ),
                (
                    "manifest_size_bytes",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="manifest 文件大小"
                    ),
                ),
                (
                    "manifest_encoding",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="manifest 编码"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_corpora",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所有者",
                    ),
                ),
            ],
            options={
                "verbose_name": "语料库",
                "verbose_name_plural": "语料库",
                "ordering": ["name", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="CorpusDocumentation",
            fields=[
                (
                    "corpus",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="documentation",
                        serialize=False,
                        to="corpora.corpus",
                        verbose_name="语料库",
                    ),
                ),
                (
                    "file_count",
                    models.PositiveIntegerField(default=0, verbose_name="文件数"),
                ),
                (
                    "document_count",
                    models.PositiveIntegerField(default=0, verbose_name="文档数"),
                ),
                (
                    "paragraph_count",
                    models.PositiveBigIntegerField(default=0, verbose_name="段落数"),
                ),
                (
                    "sentence_count",
                    models.PositiveBigIntegerField(default=0, verbose_name="句子数"),
                ),
                (
                    "token_count",
                    models.PositiveBigIntegerField(default=0, verbose_name="Token 数"),
                ),
                (
                    "type_count",
                    models.PositiveBigIntegerField(default=0, verbose_name="Type 数"),
                ),
                (
                    "segmentation_tool",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="分词工具"
                    ),
                ),
                (
                    "processing_notes",
                    models.TextField(blank=True, verbose_name="加工说明"),
                ),
                (
                    "copyright_notice",
                    models.TextField(blank=True, verbose_name="版权说明"),
                ),
                (
                    "corpus_created_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="语料形成日期"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "Corpus Documentation",
                "verbose_name_plural": "Corpus Documentation",
            },
        ),
        migrations.AddConstraint(
            model_name="corpus",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("owner__isnull", False), ("source_type", "user")),
                    models.Q(
                        ("owner__isnull", True),
                        ("source_type__in", ["teacher", "demo"]),
                    ),
                    _connector="OR",
                ),
                name="corpus_owner_matches_source_type",
            ),
        ),
    ]
