# Generated by Django 5.2.16 on 2026-07-10 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpora", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorpusFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=500, verbose_name="原始文件名"),
                ),
                (
                    "stored_path",
                    models.CharField(max_length=1500, verbose_name="存储路径"),
                ),
                (
                    "manifest_file_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="manifest 文件 ID"
                    ),
                ),
                (
                    "detected_type",
                    models.CharField(
                        choices=[
                            ("raw_zh", "中文原文"),
                            ("raw_en", "英文原文"),
                            ("aligned_tsv", "中英对齐 TSV"),
                            ("paired_raw_zh_en", "中英原文配对"),
                            ("tagged_zh", "中文词性标注"),
                            ("tagged_en", "英文词性标注"),
                            ("xml_like", "类 XML 结构"),
                            ("unknown", "待确认"),
                        ],
                        max_length=30,
                        verbose_name="检测类型",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("zh", "中文"),
                            ("en", "英文"),
                            ("zh_en", "中英双语"),
                            ("unknown", "待确认"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="语言",
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(default=0, verbose_name="文件大小"),
                ),
                (
                    "encoding",
                    models.CharField(blank=True, max_length=50, verbose_name="编码"),
                ),
                (
                    "checksum_sha256",
                    models.CharField(blank=True, max_length=64, verbose_name="SHA-256"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待加工"),
                            ("processing", "加工中"),
                            ("ready", "已加工"),
                            ("failed", "加工失败"),
                            ("disabled", "已停用"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登记时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="corpora.corpus",
                        verbose_name="语料库",
                    ),
                ),
            ],
            options={
                "verbose_name": "语料文件",
                "verbose_name_plural": "语料文件",
                "ordering": ["created_at", "original_filename"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("corpus", "stored_path"),
                        name="unique_corpus_stored_path",
                    )
                ],
            },
        ),
    ]
