# Generated by Django 5.2.16 on 2026-08-11 05:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpora", "0003_alter_corpus_corpus_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="corpus",
            index=models.Index(
                fields=["source_type", "status", "access_level"],
                name="corpus_visibility_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="corpusfile",
            index=models.Index(
                fields=["corpus", "status"], name="corpus_file_status_idx"
            ),
        ),
    ]
