# Generated by Django 5.2.16 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpora", "0004_query_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="corpusdocumentation",
            options={"verbose_name": "语料说明", "verbose_name_plural": "语料说明"},
        ),
        migrations.AlterField(
            model_name="corpusdocumentation",
            name="token_count",
            field=models.PositiveBigIntegerField(default=0, verbose_name="词元数"),
        ),
        migrations.AlterField(
            model_name="corpusdocumentation",
            name="type_count",
            field=models.PositiveBigIntegerField(default=0, verbose_name="词型数"),
        ),
    ]
