# Generated by Django 5.2.17 on 2026-08-22 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0005_alter_corpusdocumentation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='授权时间')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='corpora.corpus', verbose_name='语料库')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_corpus_accesses', to=settings.AUTH_USER_MODEL, verbose_name='授权管理员')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpus_access_grants', to=settings.AUTH_USER_MODEL, verbose_name='获授权用户')),
            ],
            options={
                'verbose_name': '语料可见授权',
                'verbose_name_plural': '语料可见授权',
                'indexes': [models.Index(fields=['user', 'corpus'], name='corpus_grant_user_corpus_idx')],
                'constraints': [models.UniqueConstraint(fields=('corpus', 'user'), name='unique_corpus_access_grant')],
            },
        ),
    ]
