// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/corpus_auditor/v1/auditor.proto

package auditorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditOptions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LowConfidence  float64                `protobuf:"fixed64,1,opt,name=low_confidence,json=lowConfidence,proto3" json:"low_confidence,omitempty"`
	MinLengthRatio float64                `protobuf:"fixed64,2,opt,name=min_length_ratio,json=minLengthRatio,proto3" json:"min_length_ratio,omitempty"`
	MaxLengthRatio float64                `protobuf:"fixed64,3,opt,name=max_length_ratio,json=maxLengthRatio,proto3" json:"max_length_ratio,omitempty"`
	MaxAnomalies   int32                  `protobuf:"varint,4,opt,name=max_anomalies,json=maxAnomalies,proto3" json:"max_anomalies,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuditOptions) Reset() {
	*x = AuditOptions{}
	mi := &file_api_proto_corpus_auditor_v1_auditor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditOptions) ProtoMessage() {}

func (x *AuditOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_corpus_auditor_v1_auditor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditOptions.ProtoReflect.Descriptor instead.
func (*AuditOptions) Descriptor() ([]byte, []int) {
	return file_api_proto_corpus_auditor_v1_auditor_proto_rawDescGZIP(), []int{0}
}

func (x *AuditOptions) GetLowConfidence() float64 {
	if x != nil {
		return x.LowConfidence
	}
	return 0
}

func (x *AuditOptions) GetMinLengthRatio() float64 {
	if x != nil {
		return x.MinLengthRatio
	}
	return 0
}

func (x *AuditOptions) GetMaxLengthRatio() float64 {
	if x != nil {
		return x.MaxLengthRatio
	}
	return 0
}

func (x *AuditOptions) GetMaxAnomalies() int32 {
	if x != nil {
		return x.MaxAnomalies
	}
	return 0
}

type SubmitAuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	InputRef      string                 `protobuf:"bytes,2,opt,name=input_ref,json=inputRef,proto3" json:"input_ref,omitempty"`
	OutputPrefix  string                 `protobuf:"bytes,3,opt,name=output_prefix,json=outputPrefix,proto3" json:"output_prefix,omitempty"`
	CallbackPath  string                 `protobuf:"bytes,4,opt,name=callback_path,json=callbackPath,proto3" json:"callback_path,omitempty"`
	Options       *AuditOptions          `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAuditRequest) Reset() {
	*x = SubmitAuditRequest{}
	mi := &file_api_proto_corpus_auditor_v1_auditor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAuditRequest) ProtoMessage() {}

func (x *SubmitAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_corpus_auditor_v1_auditor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAuditRequest.ProtoReflect.Descriptor instead.
func (*SubmitAuditRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_corpus_auditor_v1_auditor_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitAuditRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitAuditRequest) GetInputRef() string {
	if x != nil {
		return x.InputRef
	}
	return ""
}

func (x *SubmitAuditRequest) GetOutputPrefix() string {
	if x != nil {
		return x.OutputPrefix
	}
	return ""
}

func (x *SubmitAuditRequest) GetCallbackPath() string {
	if x != nil {
		return x.CallbackPath
	}
	return ""
}

func (x *SubmitAuditRequest) GetOptions() *AuditOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type GetAuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditRequest) Reset() {
	*x = GetAuditRequest{}
	mi := &file_api_proto_corpus_auditor_v1_auditor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditRequest) ProtoMessage() {}

func (x *GetAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_corpus_auditor_v1_auditor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditRequest.ProtoReflect.Descriptor instead.
func (*GetAuditRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_corpus_auditor_v1_auditor_proto_rawDescGZIP(), []int{2}
}

func (x *GetAuditRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelAuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAuditRequest) Reset() {
	*x = CancelAuditRequest{}
	mi := &file_api_proto_corpus_auditor_v1_auditor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAuditRequest) ProtoMessage() {}

func (x *CancelAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_corpus_auditor_v1_auditor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAuditRequest.ProtoReflect.Descriptor instead.
func (*CancelAuditRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_corpus_auditor_v1_auditor_proto_rawDescGZIP(), []int{3}
}

func (x *CancelAuditRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type SubmitBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*SubmitAuditRequest  `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitBatchRequest) Reset() {
	*x = SubmitBatchRequest{}
	mi := &file_api_proto_corpus_auditor_v1_auditor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitBatchRequest) ProtoMessage() {}

func (x *SubmitBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_corpus_auditor_v1_auditor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitBatchRequest.ProtoReflect.Descriptor instead.
func (*SubmitBatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_corpus_auditor_v1_auditor_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitBatchRequest) GetJobs() []*SubmitAuditRequest {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type CallbackDelivery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivered     bool                   `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"`
	Attempts      int32                  `protobuf:"varint,2,opt,name=attempts,proto3" json:"attempts,omitempty"`
	NextAt        string                 `protobuf:"bytes,3,opt,name=next_at,json=nextAt,proto3" json:"next_at,omitempty"`
	LastError     string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackDelivery) Reset() {
	*x = CallbackDelivery{}
	mi := &file_api_proto_corpus_auditor_v1_auditor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackDelivery) ProtoMessage() {}

func (x *CallbackDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_corpus_auditor_v1_auditor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackDelivery.ProtoReflect.Descriptor instead.
func (*CallbackDelivery) Descriptor() ([]byte, []int) {
	return file_api_proto_corpus_auditor_v1_auditor_proto_rawDescGZIP(), []int{5}
}

func (x *CallbackDelivery) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

func (x *CallbackDelivery) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *CallbackDelivery) GetNextAt() string {
	if x != nil {
		return x.NextAt
	}
	return ""
}

func (x *CallbackDelivery) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type AuditJob struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State          string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Attempt        int32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	InputRef       string                 `protobuf:"bytes,4,opt,name=input_ref,json=inputRef,proto3" json:"input_ref,omitempty"`
	OutputPrefix   string                 `protobuf:"bytes,5,opt,name=output_prefix,json=outputPrefix,proto3" json:"output_prefix,omitempty"`
	ReportRef      string                 `protobuf:"bytes,6,opt,name=report_ref,json=reportRef,proto3" json:"report_ref,omitempty"`
	AnomaliesRef   string                 `protobuf:"bytes,7,opt,name=anomalies_ref,json=anomaliesRef,proto3" json:"anomalies_ref,omitempty"`
	ErrorCode      string                 `protobuf:"bytes,8,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Callback       *CallbackDelivery      `protobuf:"bytes,10,opt,name=callback,proto3" json:"callback,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Summary        *structpb.Struct       `protobuf:"bytes,13,opt,name=summary,proto3" json:"summary,omitempty"`
	AuditorVersion string                 `protobuf:"bytes,14,opt,name=auditor_version,json=auditorVersion,proto3" json:"auditor_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuditJob) Reset() {
	*x = AuditJob{}
	mi := &file_api_proto_corpus_auditor_v1_auditor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditJob) ProtoMessage() {}

func (x *AuditJob) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_corpus_auditor_v1_auditor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditJob.ProtoReflect.Descriptor instead.
func (*AuditJob) Descriptor() ([]byte, []int) {
	return file_api_proto_corpus_auditor_v1_auditor_proto_rawDescGZIP(), []int{6}
}

func (x *AuditJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditJob) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AuditJob) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *AuditJob) GetInputRef() string {
	if x != nil {
		return x.InputRef
	}
	return ""
}

func (x *AuditJob) GetOutputPrefix() string {
	if x != nil {
		return x.OutputPrefix
	}
	return ""
}

func (x *AuditJob) GetReportRef() string {
	if x != nil {
		return x.ReportRef
	}
	return ""
}

func (x *AuditJob) GetAnomaliesRef() string {
	if x != nil {
		return x.AnomaliesRef
	}
	return ""
}

func (x *AuditJob) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *AuditJob) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AuditJob) GetCallback() *CallbackDelivery {
	if x != nil {
		return x.Callback
	}
	return nil
}

func (x *AuditJob) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AuditJob) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *AuditJob) GetSummary() *structpb.Struct {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *AuditJob) GetAuditorVersion() string {
	if x != nil {
		return x.AuditorVersion
	}
	return ""
}

type SubmitBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*AuditJob            `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitBatchResponse) Reset() {
	*x = SubmitBatchResponse{}
	mi := &file_api_proto_corpus_auditor_v1_auditor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitBatchResponse) ProtoMessage() {}

func (x *SubmitBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_corpus_auditor_v1_auditor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitBatchResponse.ProtoReflect.Descriptor instead.
func (*SubmitBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_corpus_auditor_v1_auditor_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitBatchResponse) GetJobs() []*AuditJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_corpus_auditor_v1_auditor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_corpus_auditor_v1_auditor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_corpus_auditor_v1_auditor_proto_rawDescGZIP(), []int{8}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

var File_api_proto_corpus_auditor_v1_auditor_proto protoreflect.FileDescriptor

const file_api_proto_corpus_auditor_v1_auditor_proto_rawDesc = "" +
	"\n" +
	")api/proto/corpus_auditor/v1/auditor.proto\x12\x11corpus_auditor.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xae\x01\n" +
	"\fAuditOptions\x12%\n" +
	"\x0elow_confidence\x18\x01 \x01(\x01R\rlowConfidence\x12(\n" +
	"\x10min_length_ratio\x18\x02 \x01(\x01R\x0eminLengthRatio\x12(\n" +
	"\x10max_length_ratio\x18\x03 \x01(\x01R\x0emaxLengthRatio\x12#\n" +
	"\rmax_anomalies\x18\x04 \x01(\x05R\fmaxAnomalies\"\xcd\x01\n" +
	"\x12SubmitAuditRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tinput_ref\x18\x02 \x01(\tR\binputRef\x12#\n" +
	"\routput_prefix\x18\x03 \x01(\tR\foutputPrefix\x12#\n" +
	"\rcallback_path\x18\x04 \x01(\tR\fcallbackPath\x129\n" +
	"\aoptions\x18\x05 \x01(\v2\x1f.corpus_auditor.v1.AuditOptionsR\aoptions\"(\n" +
	"\x0fGetAuditRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"+\n" +
	"\x12CancelAuditRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"O\n" +
	"\x12SubmitBatchRequest\x129\n" +
	"\x04jobs\x18\x01 \x03(\v2%.corpus_auditor.v1.SubmitAuditRequestR\x04jobs\"\x84\x01\n" +
	"\x10CallbackDelivery\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\bR\tdelivered\x12\x1a\n" +
	"\battempts\x18\x02 \x01(\x05R\battempts\x12\x17\n" +
	"\anext_at\x18\x03 \x01(\tR\x06nextAt\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\"\xef\x03\n" +
	"\bAuditJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\x12\x1b\n" +
	"\tinput_ref\x18\x04 \x01(\tR\binputRef\x12#\n" +
	"\routput_prefix\x18\x05 \x01(\tR\foutputPrefix\x12\x1d\n" +
	"\n" +
	"report_ref\x18\x06 \x01(\tR\treportRef\x12#\n" +
	"\ranomalies_ref\x18\a \x01(\tR\fanomaliesRef\x12\x1d\n" +
	"\n" +
	"error_code\x18\b \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x12?\n" +
	"\bcallback\x18\n" +
	" \x01(\v2#.corpus_auditor.v1.CallbackDeliveryR\bcallback\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\x121\n" +
	"\asummary\x18\r \x01(\v2\x17.google.protobuf.StructR\asummary\x12'\n" +
	"\x0fauditor_version\x18\x0e \x01(\tR\x0eauditorVersion\"F\n" +
	"\x13SubmitBatchResponse\x12/\n" +
	"\x04jobs\x18\x01 \x03(\v2\x1b.corpus_auditor.v1.AuditJobR\x04jobs\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice2\xa5\x03\n" +
	"\rCorpusAuditor\x12Q\n" +
	"\vSubmitAudit\x12%.corpus_auditor.v1.SubmitAuditRequest\x1a\x1b.corpus_auditor.v1.AuditJob\x12K\n" +
	"\bGetAudit\x12\".corpus_auditor.v1.GetAuditRequest\x1a\x1b.corpus_auditor.v1.AuditJob\x12Q\n" +
	"\vCancelAudit\x12%.corpus_auditor.v1.CancelAuditRequest\x1a\x1b.corpus_auditor.v1.AuditJob\x12\\\n" +
	"\vSubmitBatch\x12%.corpus_auditor.v1.SubmitBatchRequest\x1a&.corpus_auditor.v1.SubmitBatchResponse\x12C\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a!.corpus_auditor.v1.HealthResponseBFZDcorpus-platform/corpus-auditor/api/proto/corpus_auditor/v1;auditorv1b\x06proto3"

var (
	file_api_proto_corpus_auditor_v1_auditor_proto_rawDescOnce sync.Once
	file_api_proto_corpus_auditor_v1_auditor_proto_rawDescData []byte
)

func file_api_proto_corpus_auditor_v1_auditor_proto_rawDescGZIP() []byte {
	file_api_proto_corpus_auditor_v1_auditor_proto_rawDescOnce.Do(func() {
		file_api_proto_corpus_auditor_v1_auditor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_corpus_auditor_v1_auditor_proto_rawDesc), len(file_api_proto_corpus_auditor_v1_auditor_proto_rawDesc)))
	})
	return file_api_proto_corpus_auditor_v1_auditor_proto_rawDescData
}

var file_api_proto_corpus_auditor_v1_auditor_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_corpus_auditor_v1_auditor_proto_goTypes = []any{
	(*AuditOptions)(nil),        // 0: corpus_auditor.v1.AuditOptions
	(*SubmitAuditRequest)(nil),  // 1: corpus_auditor.v1.SubmitAuditRequest
	(*GetAuditRequest)(nil),     // 2: corpus_auditor.v1.GetAuditRequest
	(*CancelAuditRequest)(nil),  // 3: corpus_auditor.v1.CancelAuditRequest
	(*SubmitBatchRequest)(nil),  // 4: corpus_auditor.v1.SubmitBatchRequest
	(*CallbackDelivery)(nil),    // 5: corpus_auditor.v1.CallbackDelivery
	(*AuditJob)(nil),            // 6: corpus_auditor.v1.AuditJob
	(*SubmitBatchResponse)(nil), // 7: corpus_auditor.v1.SubmitBatchResponse
	(*HealthResponse)(nil),      // 8: corpus_auditor.v1.HealthResponse
	(*structpb.Struct)(nil),     // 9: google.protobuf.Struct
	(*emptypb.Empty)(nil),       // 10: google.protobuf.Empty
}
var file_api_proto_corpus_auditor_v1_auditor_proto_depIdxs = []int32{
	0,  // 0: corpus_auditor.v1.SubmitAuditRequest.options:type_name -> corpus_auditor.v1.AuditOptions
	1,  // 1: corpus_auditor.v1.SubmitBatchRequest.jobs:type_name -> corpus_auditor.v1.SubmitAuditRequest
	5,  // 2: corpus_auditor.v1.AuditJob.callback:type_name -> corpus_auditor.v1.CallbackDelivery
	9,  // 3: corpus_auditor.v1.AuditJob.summary:type_name -> google.protobuf.Struct
	6,  // 4: corpus_auditor.v1.SubmitBatchResponse.jobs:type_name -> corpus_auditor.v1.AuditJob
	1,  // 5: corpus_auditor.v1.CorpusAuditor.SubmitAudit:input_type -> corpus_auditor.v1.SubmitAuditRequest
	2,  // 6: corpus_auditor.v1.CorpusAuditor.GetAudit:input_type -> corpus_auditor.v1.GetAuditRequest
	3,  // 7: corpus_auditor.v1.CorpusAuditor.CancelAudit:input_type -> corpus_auditor.v1.CancelAuditRequest
	4,  // 8: corpus_auditor.v1.CorpusAuditor.SubmitBatch:input_type -> corpus_auditor.v1.SubmitBatchRequest
	10, // 9: corpus_auditor.v1.CorpusAuditor.Health:input_type -> google.protobuf.Empty
	6,  // 10: corpus_auditor.v1.CorpusAuditor.SubmitAudit:output_type -> corpus_auditor.v1.AuditJob
	6,  // 11: corpus_auditor.v1.CorpusAuditor.GetAudit:output_type -> corpus_auditor.v1.AuditJob
	6,  // 12: corpus_auditor.v1.CorpusAuditor.CancelAudit:output_type -> corpus_auditor.v1.AuditJob
	7,  // 13: corpus_auditor.v1.CorpusAuditor.SubmitBatch:output_type -> corpus_auditor.v1.SubmitBatchResponse
	8,  // 14: corpus_auditor.v1.CorpusAuditor.Health:output_type -> corpus_auditor.v1.HealthResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_corpus_auditor_v1_auditor_proto_init() }
func file_api_proto_corpus_auditor_v1_auditor_proto_init() {
	if File_api_proto_corpus_auditor_v1_auditor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_corpus_auditor_v1_auditor_proto_rawDesc), len(file_api_proto_corpus_auditor_v1_auditor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_corpus_auditor_v1_auditor_proto_goTypes,
		DependencyIndexes: file_api_proto_corpus_auditor_v1_auditor_proto_depIdxs,
		MessageInfos:      file_api_proto_corpus_auditor_v1_auditor_proto_msgTypes,
	}.Build()
	File_api_proto_corpus_auditor_v1_auditor_proto = out.File
	file_api_proto_corpus_auditor_v1_auditor_proto_goTypes = nil
	file_api_proto_corpus_auditor_v1_auditor_proto_depIdxs = nil
}
