// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/proto/corpus_auditor/v1/auditor.proto

package auditorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CorpusAuditor_SubmitAudit_FullMethodName = "/corpus_auditor.v1.CorpusAuditor/SubmitAudit"
	CorpusAuditor_GetAudit_FullMethodName    = "/corpus_auditor.v1.CorpusAuditor/GetAudit"
	CorpusAuditor_CancelAudit_FullMethodName = "/corpus_auditor.v1.CorpusAuditor/CancelAudit"
	CorpusAuditor_SubmitBatch_FullMethodName = "/corpus_auditor.v1.CorpusAuditor/SubmitBatch"
	CorpusAuditor_Health_FullMethodName      = "/corpus_auditor.v1.CorpusAuditor/Health"
)

// CorpusAuditorClient is the client API for CorpusAuditor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CorpusAuditorClient interface {
	SubmitAudit(ctx context.Context, in *SubmitAuditRequest, opts ...grpc.CallOption) (*AuditJob, error)
	GetAudit(ctx context.Context, in *GetAuditRequest, opts ...grpc.CallOption) (*AuditJob, error)
	CancelAudit(ctx context.Context, in *CancelAuditRequest, opts ...grpc.CallOption) (*AuditJob, error)
	SubmitBatch(ctx context.Context, in *SubmitBatchRequest, opts ...grpc.CallOption) (*SubmitBatchResponse, error)
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type corpusAuditorClient struct {
	cc grpc.ClientConnInterface
}

func NewCorpusAuditorClient(cc grpc.ClientConnInterface) CorpusAuditorClient {
	return &corpusAuditorClient{cc}
}

func (c *corpusAuditorClient) SubmitAudit(ctx context.Context, in *SubmitAuditRequest, opts ...grpc.CallOption) (*AuditJob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditJob)
	err := c.cc.Invoke(ctx, CorpusAuditor_SubmitAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corpusAuditorClient) GetAudit(ctx context.Context, in *GetAuditRequest, opts ...grpc.CallOption) (*AuditJob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditJob)
	err := c.cc.Invoke(ctx, CorpusAuditor_GetAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corpusAuditorClient) CancelAudit(ctx context.Context, in *CancelAuditRequest, opts ...grpc.CallOption) (*AuditJob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditJob)
	err := c.cc.Invoke(ctx, CorpusAuditor_CancelAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corpusAuditorClient) SubmitBatch(ctx context.Context, in *SubmitBatchRequest, opts ...grpc.CallOption) (*SubmitBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitBatchResponse)
	err := c.cc.Invoke(ctx, CorpusAuditor_SubmitBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corpusAuditorClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, CorpusAuditor_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CorpusAuditorServer is the server API for CorpusAuditor service.
// All implementations must embed UnimplementedCorpusAuditorServer
// for forward compatibility.
type CorpusAuditorServer interface {
	SubmitAudit(context.Context, *SubmitAuditRequest) (*AuditJob, error)
	GetAudit(context.Context, *GetAuditRequest) (*AuditJob, error)
	CancelAudit(context.Context, *CancelAuditRequest) (*AuditJob, error)
	SubmitBatch(context.Context, *SubmitBatchRequest) (*SubmitBatchResponse, error)
	Health(context.Context, *emptypb.Empty) (*HealthResponse, error)
	mustEmbedUnimplementedCorpusAuditorServer()
}

// UnimplementedCorpusAuditorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCorpusAuditorServer struct{}

func (UnimplementedCorpusAuditorServer) SubmitAudit(context.Context, *SubmitAuditRequest) (*AuditJob, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitAudit not implemented")
}
func (UnimplementedCorpusAuditorServer) GetAudit(context.Context, *GetAuditRequest) (*AuditJob, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAudit not implemented")
}
func (UnimplementedCorpusAuditorServer) CancelAudit(context.Context, *CancelAuditRequest) (*AuditJob, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelAudit not implemented")
}
func (UnimplementedCorpusAuditorServer) SubmitBatch(context.Context, *SubmitBatchRequest) (*SubmitBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitBatch not implemented")
}
func (UnimplementedCorpusAuditorServer) Health(context.Context, *emptypb.Empty) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCorpusAuditorServer) mustEmbedUnimplementedCorpusAuditorServer() {}
func (UnimplementedCorpusAuditorServer) testEmbeddedByValue()                       {}

// UnsafeCorpusAuditorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CorpusAuditorServer will
// result in compilation errors.
type UnsafeCorpusAuditorServer interface {
	mustEmbedUnimplementedCorpusAuditorServer()
}

func RegisterCorpusAuditorServer(s grpc.ServiceRegistrar, srv CorpusAuditorServer) {
	// If the following call pancis, it indicates UnimplementedCorpusAuditorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CorpusAuditor_ServiceDesc, srv)
}

func _CorpusAuditor_SubmitAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorpusAuditorServer).SubmitAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorpusAuditor_SubmitAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorpusAuditorServer).SubmitAudit(ctx, req.(*SubmitAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorpusAuditor_GetAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorpusAuditorServer).GetAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorpusAuditor_GetAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorpusAuditorServer).GetAudit(ctx, req.(*GetAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorpusAuditor_CancelAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorpusAuditorServer).CancelAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorpusAuditor_CancelAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorpusAuditorServer).CancelAudit(ctx, req.(*CancelAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorpusAuditor_SubmitBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorpusAuditorServer).SubmitBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorpusAuditor_SubmitBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorpusAuditorServer).SubmitBatch(ctx, req.(*SubmitBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorpusAuditor_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorpusAuditorServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorpusAuditor_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorpusAuditorServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CorpusAuditor_ServiceDesc is the grpc.ServiceDesc for CorpusAuditor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CorpusAuditor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "corpus_auditor.v1.CorpusAuditor",
	HandlerType: (*CorpusAuditorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitAudit",
			Handler:    _CorpusAuditor_SubmitAudit_Handler,
		},
		{
			MethodName: "GetAudit",
			Handler:    _CorpusAuditor_GetAudit_Handler,
		},
		{
			MethodName: "CancelAudit",
			Handler:    _CorpusAuditor_CancelAudit_Handler,
		},
		{
			MethodName: "SubmitBatch",
			Handler:    _CorpusAuditor_SubmitBatch_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _CorpusAuditor_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/corpus_auditor/v1/auditor.proto",
}
