# Generated by Django 5.2.16 on 2026-08-11 10:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        choices=[
                            ("processing.process_corpus", "加工语料"),
                            ("exports.build_export", "生成导出"),
                        ],
                        max_length=100,
                        verbose_name="Celery 任务",
                    ),
                ),
                (
                    "aggregate_id",
                    models.UUIDField(db_index=True, verbose_name="业务任务 ID"),
                ),
                (
                    "deduplication_key",
                    models.CharField(
                        max_length=180, unique=True, verbose_name="幂等键"
                    ),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="任务参数")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待投递"),
                            ("publishing", "投递中"),
                            ("published", "已投递"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="投递状态",
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(default=0, verbose_name="投递尝试次数"),
                ),
                (
                    "available_at",
                    models.DateTimeField(db_index=True, verbose_name="下次可投递时间"),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="投递租约截止",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="投递完成时间"
                    ),
                ),
                ("last_error", models.TextField(blank=True, verbose_name="最近错误")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "事务外盒事件",
                "verbose_name_plural": "事务外盒事件",
                "ordering": ["available_at", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "available_at"], name="outbox_pending_idx"
                    ),
                    models.Index(
                        fields=["status", "locked_until"], name="outbox_lease_idx"
                    ),
                    models.Index(
                        fields=["status", "published_at"], name="outbox_cleanup_idx"
                    ),
                ],
            },
        ),
    ]
