# Generated by Django 5.2.16 on 2026-08-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outbox", "0001_transactional_outbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboxevent",
            name="dead_lettered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="replay_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="outboxevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "等待投递"),
                    ("publishing", "投递中"),
                    ("published", "已投递"),
                    ("dead_letter", "Dead letter"),
                ],
                default="pending",
                max_length=20,
                verbose_name="投递状态",
            ),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(
                fields=["status", "dead_lettered_at"], name="outbox_dead_letter_idx"
            ),
        ),
    ]
