# Generated by Django 5.2.16 on 2026-08-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outbox", "0002_add_dead_letter_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outboxevent",
            name="task_name",
            field=models.CharField(
                choices=[
                    ("processing.process_corpus", "加工语料"),
                    ("exports.build_export", "生成导出"),
                    ("audits.audit_parallel_corpus", "平行语料审计"),
                ],
                max_length=100,
                verbose_name="Celery 任务",
            ),
        ),
    ]
