# Generated by Django 5.2.16 on 2026-08-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outbox", "0004_corpus_agent_harness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outboxevent",
            name="task_name",
            field=models.CharField(
                choices=[
                    ("processing.process_corpus", "加工语料"),
                    ("exports.build_export", "生成导出"),
                    ("audits.audit_parallel_corpus", "平行语料审计"),
                    ("agent.run_corpus_agent", "Run corpus Agent"),
                    (
                        "audits.publish_parallel_audit_command",
                        "Publish parallel audit command",
                    ),
                ],
                max_length=100,
                verbose_name="Celery 任务",
            ),
        ),
    ]
