# Generated by Django 5.2.17 on 2026-09-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outbox", "0007_supported_task_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outboxevent",
            name="task_name",
            field=models.CharField(
                choices=[
                    ("processing.process_corpus", "加工语料"),
                    ("exports.build_export", "生成导出"),
                    ("audits.audit_parallel_corpus", "平行语料审计"),
                    (
                        "audits.publish_parallel_audit_command",
                        "Publish parallel audit command",
                    ),
                ],
                max_length=100,
                verbose_name="Celery 任务",
            ),
        ),
    ]
